### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by aaronaftab** [jmather625/OSM_buildingdetector#17]
Once viable classifier exists, potential to automate mapping process

**Comment by jaa2** [comment]
Automating the mapping process sounds like a good idea, but if we take that route, we must do so with caution. I would recommend reading the [Automated Edits page](https://wiki.openstreetmap.org/wiki/Automated_edits) on the OSM wiki as well as the [Automated Edits Code of Conduct](https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct).

I don't think creating new buildings would be difficult to revert (i.e. it would probably be okay with the code of conduct), but we certainly need to make sure we do not create new buildings that don't actually exist or new buildings that already exist on the map.

With what our program is doing, all of our edits need to be human-verified. It might be better to have users verify their edits by clicking on the buildings from the imagery, which forces them to visually check to make sure they are doing what they want to do.
