### ISSUE TITLE
No such file or directory: 'default_images/tmp.PNG'

### ISSUE THREAD

**Issue by oneOfThePeople** [jmather625/OSM_buildingdetector#20]
i tried to run the code and i got this error

Mask_RCNN_Detect.py", line 53, in __init__
    np.array(Image.open('default_images/tmp.PNG'))[:, :, :3])])
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2543, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'default_images/tmp.PNG'

thank you

**Comment by jmathur25** [comment]
Hi,

Whoops I forgot to manually add that file after ignoring all .pngs in the .gitignore. It should work now.
